/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AuthEmailPasswordLoginRequest
    /// </summary>
    [DataContract(Name = "authEmailPasswordLoginRequest")]
    public partial class AuthEmailPasswordLoginRequest : IEquatable<AuthEmailPasswordLoginRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthEmailPasswordLoginRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthEmailPasswordLoginRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthEmailPasswordLoginRequest" /> class.
        /// </summary>
        /// <param name="createUser">Whether to create a user, if it does not exist.</param>
        /// <param name="email">Email address used as login (required).</param>
        /// <param name="loginMetadata">loginMetadata.</param>
        /// <param name="password">Password used for login (required).</param>
        public AuthEmailPasswordLoginRequest(bool createUser = default(bool), string email = default(string), AuthLoginMetadata loginMetadata = default(AuthLoginMetadata), string password = default(string))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for AuthEmailPasswordLoginRequest and cannot be null");
            }
            this.Email = email;
            // to ensure "password" is required (not null)
            if (password == null)
            {
                throw new ArgumentNullException("password is a required property for AuthEmailPasswordLoginRequest and cannot be null");
            }
            this.Password = password;
            this.CreateUser = createUser;
            this.LoginMetadata = loginMetadata;
        }

        /// <summary>
        /// Whether to create a user, if it does not exist
        /// </summary>
        /// <value>Whether to create a user, if it does not exist</value>
        [DataMember(Name = "create_user", EmitDefaultValue = true)]
        public bool CreateUser { get; set; }

        /// <summary>
        /// Email address used as login
        /// </summary>
        /// <value>Email address used as login</value>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets LoginMetadata
        /// </summary>
        [DataMember(Name = "login_metadata", EmitDefaultValue = false)]
        public AuthLoginMetadata LoginMetadata { get; set; }

        /// <summary>
        /// Password used for login
        /// </summary>
        /// <value>Password used for login</value>
        [DataMember(Name = "password", IsRequired = true, EmitDefaultValue = true)]
        public string Password { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthEmailPasswordLoginRequest {\n");
            sb.Append("  CreateUser: ").Append(CreateUser).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  LoginMetadata: ").Append(LoginMetadata).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthEmailPasswordLoginRequest);
        }

        /// <summary>
        /// Returns true if AuthEmailPasswordLoginRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthEmailPasswordLoginRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthEmailPasswordLoginRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CreateUser == input.CreateUser ||
                    this.CreateUser.Equals(input.CreateUser)
                ) && 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.LoginMetadata == input.LoginMetadata ||
                    (this.LoginMetadata != null &&
                    this.LoginMetadata.Equals(input.LoginMetadata))
                ) && 
                (
                    this.Password == input.Password ||
                    (this.Password != null &&
                    this.Password.Equals(input.Password))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CreateUser.GetHashCode();
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                if (this.LoginMetadata != null)
                {
                    hashCode = (hashCode * 59) + this.LoginMetadata.GetHashCode();
                }
                if (this.Password != null)
                {
                    hashCode = (hashCode * 59) + this.Password.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
