/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AuthUpdateUsernamePasswordRequest
    /// </summary>
    [DataContract(Name = "authUpdateUsernamePasswordRequest")]
    public partial class AuthUpdateUsernamePasswordRequest : IEquatable<AuthUpdateUsernamePasswordRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthUpdateUsernamePasswordRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthUpdateUsernamePasswordRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthUpdateUsernamePasswordRequest" /> class.
        /// </summary>
        /// <param name="newPassword">New password to be set (required).</param>
        /// <param name="oldPassword">Old password to be verified (required).</param>
        /// <param name="username">User&#39;s login ID (required).</param>
        public AuthUpdateUsernamePasswordRequest(string newPassword = default(string), string oldPassword = default(string), string username = default(string))
        {
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for AuthUpdateUsernamePasswordRequest and cannot be null");
            }
            this.NewPassword = newPassword;
            // to ensure "oldPassword" is required (not null)
            if (oldPassword == null)
            {
                throw new ArgumentNullException("oldPassword is a required property for AuthUpdateUsernamePasswordRequest and cannot be null");
            }
            this.OldPassword = oldPassword;
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for AuthUpdateUsernamePasswordRequest and cannot be null");
            }
            this.Username = username;
        }

        /// <summary>
        /// New password to be set
        /// </summary>
        /// <value>New password to be set</value>
        [DataMember(Name = "new_password", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Old password to be verified
        /// </summary>
        /// <value>Old password to be verified</value>
        [DataMember(Name = "old_password", IsRequired = true, EmitDefaultValue = true)]
        public string OldPassword { get; set; }

        /// <summary>
        /// User&#39;s login ID
        /// </summary>
        /// <value>User&#39;s login ID</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthUpdateUsernamePasswordRequest {\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  OldPassword: ").Append(OldPassword).Append("\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthUpdateUsernamePasswordRequest);
        }

        /// <summary>
        /// Returns true if AuthUpdateUsernamePasswordRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthUpdateUsernamePasswordRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthUpdateUsernamePasswordRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NewPassword == input.NewPassword ||
                    (this.NewPassword != null &&
                    this.NewPassword.Equals(input.NewPassword))
                ) && 
                (
                    this.OldPassword == input.OldPassword ||
                    (this.OldPassword != null &&
                    this.OldPassword.Equals(input.OldPassword))
                ) && 
                (
                    this.Username == input.Username ||
                    (this.Username != null &&
                    this.Username.Equals(input.Username))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewPassword != null)
                {
                    hashCode = (hashCode * 59) + this.NewPassword.GetHashCode();
                }
                if (this.OldPassword != null)
                {
                    hashCode = (hashCode * 59) + this.OldPassword.GetHashCode();
                }
                if (this.Username != null)
                {
                    hashCode = (hashCode * 59) + this.Username.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
