/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AuthAppleLoginRequest
    /// </summary>
    [DataContract(Name = "authAppleLoginRequest")]
    public partial class AuthAppleLoginRequest : IEquatable<AuthAppleLoginRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthAppleLoginRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthAppleLoginRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthAppleLoginRequest" /> class.
        /// </summary>
        /// <param name="createUser">Whether to create a user, if it does not exist.</param>
        /// <param name="token">Apple token generated on the client (required).</param>
        public AuthAppleLoginRequest(bool createUser = default(bool), string token = default(string))
        {
            // to ensure "token" is required (not null)
            if (token == null)
            {
                throw new ArgumentNullException("token is a required property for AuthAppleLoginRequest and cannot be null");
            }
            this.Token = token;
            this.CreateUser = createUser;
        }

        /// <summary>
        /// Whether to create a user, if it does not exist
        /// </summary>
        /// <value>Whether to create a user, if it does not exist</value>
        [DataMember(Name = "create_user", EmitDefaultValue = true)]
        public bool CreateUser { get; set; }

        /// <summary>
        /// Apple token generated on the client
        /// </summary>
        /// <value>Apple token generated on the client</value>
        [DataMember(Name = "token", IsRequired = true, EmitDefaultValue = true)]
        public string Token { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthAppleLoginRequest {\n");
            sb.Append("  CreateUser: ").Append(CreateUser).Append("\n");
            sb.Append("  Token: ").Append(Token).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthAppleLoginRequest);
        }

        /// <summary>
        /// Returns true if AuthAppleLoginRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthAppleLoginRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthAppleLoginRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CreateUser == input.CreateUser ||
                    this.CreateUser.Equals(input.CreateUser)
                ) && 
                (
                    this.Token == input.Token ||
                    (this.Token != null &&
                    this.Token.Equals(input.Token))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CreateUser.GetHashCode();
                if (this.Token != null)
                {
                    hashCode = (hashCode * 59) + this.Token.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
