/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AuthUpdateEmailPasswordRequest
    /// </summary>
    [DataContract(Name = "authUpdateEmailPasswordRequest")]
    public partial class AuthUpdateEmailPasswordRequest : IEquatable<AuthUpdateEmailPasswordRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthUpdateEmailPasswordRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthUpdateEmailPasswordRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthUpdateEmailPasswordRequest" /> class.
        /// </summary>
        /// <param name="email">Email address to update (required).</param>
        /// <param name="newPassword">New password to be set (required).</param>
        /// <param name="oldPassword">Old password to be verified. One of old_password or recovery_code is required.</param>
        /// <param name="recoveryCode">Recovery code received by the user. One of old_password or recovery_code is required.</param>
        public AuthUpdateEmailPasswordRequest(string email = default(string), string newPassword = default(string), string oldPassword = default(string), string recoveryCode = default(string))
        {
            // to ensure "email" is required (not null)
            if (email == null)
            {
                throw new ArgumentNullException("email is a required property for AuthUpdateEmailPasswordRequest and cannot be null");
            }
            this.Email = email;
            // to ensure "newPassword" is required (not null)
            if (newPassword == null)
            {
                throw new ArgumentNullException("newPassword is a required property for AuthUpdateEmailPasswordRequest and cannot be null");
            }
            this.NewPassword = newPassword;
            this.OldPassword = oldPassword;
            this.RecoveryCode = recoveryCode;
        }

        /// <summary>
        /// Email address to update
        /// </summary>
        /// <value>Email address to update</value>
        [DataMember(Name = "email", IsRequired = true, EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// New password to be set
        /// </summary>
        /// <value>New password to be set</value>
        [DataMember(Name = "new_password", IsRequired = true, EmitDefaultValue = true)]
        public string NewPassword { get; set; }

        /// <summary>
        /// Old password to be verified. One of old_password or recovery_code is required
        /// </summary>
        /// <value>Old password to be verified. One of old_password or recovery_code is required</value>
        [DataMember(Name = "old_password", EmitDefaultValue = false)]
        public string OldPassword { get; set; }

        /// <summary>
        /// Recovery code received by the user. One of old_password or recovery_code is required
        /// </summary>
        /// <value>Recovery code received by the user. One of old_password or recovery_code is required</value>
        [DataMember(Name = "recovery_code", EmitDefaultValue = false)]
        public string RecoveryCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthUpdateEmailPasswordRequest {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  NewPassword: ").Append(NewPassword).Append("\n");
            sb.Append("  OldPassword: ").Append(OldPassword).Append("\n");
            sb.Append("  RecoveryCode: ").Append(RecoveryCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthUpdateEmailPasswordRequest);
        }

        /// <summary>
        /// Returns true if AuthUpdateEmailPasswordRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthUpdateEmailPasswordRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthUpdateEmailPasswordRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.NewPassword == input.NewPassword ||
                    (this.NewPassword != null &&
                    this.NewPassword.Equals(input.NewPassword))
                ) && 
                (
                    this.OldPassword == input.OldPassword ||
                    (this.OldPassword != null &&
                    this.OldPassword.Equals(input.OldPassword))
                ) && 
                (
                    this.RecoveryCode == input.RecoveryCode ||
                    (this.RecoveryCode != null &&
                    this.RecoveryCode.Equals(input.RecoveryCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Email != null)
                {
                    hashCode = (hashCode * 59) + this.Email.GetHashCode();
                }
                if (this.NewPassword != null)
                {
                    hashCode = (hashCode * 59) + this.NewPassword.GetHashCode();
                }
                if (this.OldPassword != null)
                {
                    hashCode = (hashCode * 59) + this.OldPassword.GetHashCode();
                }
                if (this.RecoveryCode != null)
                {
                    hashCode = (hashCode * 59) + this.RecoveryCode.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
