/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AuthXLoginRequest
    /// </summary>
    [DataContract(Name = "authXLoginRequest")]
    public partial class AuthXLoginRequest : IEquatable<AuthXLoginRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthXLoginRequest" /> class.
        /// </summary>
        /// <param name="accessToken">X access token generated on the client. One of code or access_token is required.</param>
        /// <param name="code">X code generated on the client. One of code or access_token is required.</param>
        /// <param name="codeVerifier">X code verifier generated on the client.</param>
        /// <param name="createUser">Whether to create a user, if it does not exist.</param>
        /// <param name="loginMetadata">loginMetadata.</param>
        /// <param name="redirectUri">redirect url for client.</param>
        public AuthXLoginRequest(string accessToken = default(string), string code = default(string), string codeVerifier = default(string), bool createUser = default(bool), AuthLoginMetadata loginMetadata = default(AuthLoginMetadata), string redirectUri = default(string))
        {
            this.AccessToken = accessToken;
            this.Code = code;
            this.CodeVerifier = codeVerifier;
            this.CreateUser = createUser;
            this.LoginMetadata = loginMetadata;
            this.RedirectUri = redirectUri;
        }

        /// <summary>
        /// X access token generated on the client. One of code or access_token is required
        /// </summary>
        /// <value>X access token generated on the client. One of code or access_token is required</value>
        [DataMember(Name = "access_token", EmitDefaultValue = false)]
        public string AccessToken { get; set; }

        /// <summary>
        /// X code generated on the client. One of code or access_token is required
        /// </summary>
        /// <value>X code generated on the client. One of code or access_token is required</value>
        [DataMember(Name = "code", EmitDefaultValue = false)]
        public string Code { get; set; }

        /// <summary>
        /// X code verifier generated on the client
        /// </summary>
        /// <value>X code verifier generated on the client</value>
        [DataMember(Name = "code_verifier", EmitDefaultValue = false)]
        public string CodeVerifier { get; set; }

        /// <summary>
        /// Whether to create a user, if it does not exist
        /// </summary>
        /// <value>Whether to create a user, if it does not exist</value>
        [DataMember(Name = "create_user", EmitDefaultValue = true)]
        public bool CreateUser { get; set; }

        /// <summary>
        /// Gets or Sets LoginMetadata
        /// </summary>
        [DataMember(Name = "login_metadata", EmitDefaultValue = false)]
        public AuthLoginMetadata LoginMetadata { get; set; }

        /// <summary>
        /// redirect url for client
        /// </summary>
        /// <value>redirect url for client</value>
        [DataMember(Name = "redirect_uri", EmitDefaultValue = false)]
        public string RedirectUri { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthXLoginRequest {\n");
            sb.Append("  AccessToken: ").Append(AccessToken).Append("\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  CodeVerifier: ").Append(CodeVerifier).Append("\n");
            sb.Append("  CreateUser: ").Append(CreateUser).Append("\n");
            sb.Append("  LoginMetadata: ").Append(LoginMetadata).Append("\n");
            sb.Append("  RedirectUri: ").Append(RedirectUri).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthXLoginRequest);
        }

        /// <summary>
        /// Returns true if AuthXLoginRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthXLoginRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthXLoginRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccessToken == input.AccessToken ||
                    (this.AccessToken != null &&
                    this.AccessToken.Equals(input.AccessToken))
                ) && 
                (
                    this.Code == input.Code ||
                    (this.Code != null &&
                    this.Code.Equals(input.Code))
                ) && 
                (
                    this.CodeVerifier == input.CodeVerifier ||
                    (this.CodeVerifier != null &&
                    this.CodeVerifier.Equals(input.CodeVerifier))
                ) && 
                (
                    this.CreateUser == input.CreateUser ||
                    this.CreateUser.Equals(input.CreateUser)
                ) && 
                (
                    this.LoginMetadata == input.LoginMetadata ||
                    (this.LoginMetadata != null &&
                    this.LoginMetadata.Equals(input.LoginMetadata))
                ) && 
                (
                    this.RedirectUri == input.RedirectUri ||
                    (this.RedirectUri != null &&
                    this.RedirectUri.Equals(input.RedirectUri))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AccessToken != null)
                {
                    hashCode = (hashCode * 59) + this.AccessToken.GetHashCode();
                }
                if (this.Code != null)
                {
                    hashCode = (hashCode * 59) + this.Code.GetHashCode();
                }
                if (this.CodeVerifier != null)
                {
                    hashCode = (hashCode * 59) + this.CodeVerifier.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.CreateUser.GetHashCode();
                if (this.LoginMetadata != null)
                {
                    hashCode = (hashCode * 59) + this.LoginMetadata.GetHashCode();
                }
                if (this.RedirectUri != null)
                {
                    hashCode = (hashCode * 59) + this.RedirectUri.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
