/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// AuthEmailPasswordLoginResponse
    /// </summary>
    [DataContract(Name = "authEmailPasswordLoginResponse")]
    public partial class AuthEmailPasswordLoginResponse : IEquatable<AuthEmailPasswordLoginResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthEmailPasswordLoginResponse" /> class.
        /// </summary>
        /// <param name="emailVerificationRequired">Whether email verification is required or not.</param>
        /// <param name="user">user.</param>
        public AuthEmailPasswordLoginResponse(bool emailVerificationRequired = default(bool), AuthUser user = default(AuthUser))
        {
            this.EmailVerificationRequired = emailVerificationRequired;
            this.User = user;
        }

        /// <summary>
        /// Whether email verification is required or not
        /// </summary>
        /// <value>Whether email verification is required or not</value>
        [DataMember(Name = "email_verification_required", EmitDefaultValue = true)]
        public bool EmailVerificationRequired { get; set; }

        /// <summary>
        /// Gets or Sets User
        /// </summary>
        [DataMember(Name = "user", EmitDefaultValue = false)]
        public AuthUser User { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthEmailPasswordLoginResponse {\n");
            sb.Append("  EmailVerificationRequired: ").Append(EmailVerificationRequired).Append("\n");
            sb.Append("  User: ").Append(User).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as AuthEmailPasswordLoginResponse);
        }

        /// <summary>
        /// Returns true if AuthEmailPasswordLoginResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of AuthEmailPasswordLoginResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AuthEmailPasswordLoginResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.EmailVerificationRequired == input.EmailVerificationRequired ||
                    this.EmailVerificationRequired.Equals(input.EmailVerificationRequired)
                ) && 
                (
                    this.User == input.User ||
                    (this.User != null &&
                    this.User.Equals(input.User))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.EmailVerificationRequired.GetHashCode();
                if (this.User != null)
                {
                    hashCode = (hashCode * 59) + this.User.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
