/*
 * snapship
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: snapship: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// BatchUpdateUserStatisticsRequest
    /// </summary>
    [DataContract(Name = "BatchUpdateUserStatistics_request")]
    public partial class BatchUpdateUserStatisticsRequest : IEquatable<BatchUpdateUserStatisticsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchUpdateUserStatisticsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchUpdateUserStatisticsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchUpdateUserStatisticsRequest" /> class.
        /// </summary>
        /// <param name="data">Array of operations to be performed (required).</param>
        public BatchUpdateUserStatisticsRequest(List<StatisticsBatchUpdateUserStatisticsItem> data = default(List<StatisticsBatchUpdateUserStatisticsItem>))
        {
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for BatchUpdateUserStatisticsRequest and cannot be null");
            }
            this.Data = data;
        }

        /// <summary>
        /// Array of operations to be performed
        /// </summary>
        /// <value>Array of operations to be performed</value>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public List<StatisticsBatchUpdateUserStatisticsItem> Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchUpdateUserStatisticsRequest {\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatchUpdateUserStatisticsRequest);
        }

        /// <summary>
        /// Returns true if BatchUpdateUserStatisticsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of BatchUpdateUserStatisticsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchUpdateUserStatisticsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Data == input.Data ||
                    this.Data != null &&
                    input.Data != null &&
                    this.Data.SequenceEqual(input.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Data != null)
                {
                    hashCode = (hashCode * 59) + this.Data.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
