/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// InsertJsonBlobRequest
    /// </summary>
    [DataContract(Name = "InsertJsonBlob_request")]
    public partial class InsertJsonBlobRequest : IEquatable<InsertJsonBlobRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InsertJsonBlobRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InsertJsonBlobRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InsertJsonBlobRequest" /> class.
        /// </summary>
        /// <param name="ttl">Optional TTL for the blob.</param>
        /// <param name="value">JSON value to be inserted (required).</param>
        public InsertJsonBlobRequest(long ttl = default(long), Object value = default(Object))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for InsertJsonBlobRequest and cannot be null");
            }
            this.Value = value;
            this.Ttl = ttl;
        }

        /// <summary>
        /// Optional TTL for the blob
        /// </summary>
        /// <value>Optional TTL for the blob</value>
        [DataMember(Name = "ttl", EmitDefaultValue = false)]
        public long Ttl { get; set; }

        /// <summary>
        /// JSON value to be inserted
        /// </summary>
        /// <value>JSON value to be inserted</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class InsertJsonBlobRequest {\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InsertJsonBlobRequest);
        }

        /// <summary>
        /// Returns true if InsertJsonBlobRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of InsertJsonBlobRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InsertJsonBlobRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Ttl == input.Ttl ||
                    this.Ttl.Equals(input.Ttl)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Ttl.GetHashCode();
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
