/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// LeaderboardsGetScoresResponse
    /// </summary>
    [DataContract(Name = "leaderboardsGetScoresResponse")]
    public partial class LeaderboardsGetScoresResponse : IEquatable<LeaderboardsGetScoresResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardsGetScoresResponse" /> class.
        /// </summary>
        /// <param name="tier">tier.</param>
        /// <param name="userScores">List of users in the order defined by the leaderboard.</param>
        public LeaderboardsGetScoresResponse(LeaderboardsTier tier = default(LeaderboardsTier), List<LeaderboardsUserScore> userScores = default(List<LeaderboardsUserScore>))
        {
            this.Tier = tier;
            this.UserScores = userScores;
        }

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name = "tier", EmitDefaultValue = false)]
        public LeaderboardsTier Tier { get; set; }

        /// <summary>
        /// List of users in the order defined by the leaderboard
        /// </summary>
        /// <value>List of users in the order defined by the leaderboard</value>
        [DataMember(Name = "user_scores", EmitDefaultValue = false)]
        public List<LeaderboardsUserScore> UserScores { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LeaderboardsGetScoresResponse {\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  UserScores: ").Append(UserScores).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LeaderboardsGetScoresResponse);
        }

        /// <summary>
        /// Returns true if LeaderboardsGetScoresResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LeaderboardsGetScoresResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LeaderboardsGetScoresResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Tier == input.Tier ||
                    (this.Tier != null &&
                    this.Tier.Equals(input.Tier))
                ) && 
                (
                    this.UserScores == input.UserScores ||
                    this.UserScores != null &&
                    input.UserScores != null &&
                    this.UserScores.SequenceEqual(input.UserScores)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Tier != null)
                {
                    hashCode = (hashCode * 59) + this.Tier.GetHashCode();
                }
                if (this.UserScores != null)
                {
                    hashCode = (hashCode * 59) + this.UserScores.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
