/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// LeaderboardsIncrementScoreResponse
    /// </summary>
    [DataContract(Name = "leaderboardsIncrementScoreResponse")]
    public partial class LeaderboardsIncrementScoreResponse : IEquatable<LeaderboardsIncrementScoreResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LeaderboardsIncrementScoreResponse" /> class.
        /// </summary>
        /// <param name="rank">Latest rank to be returned.</param>
        /// <param name="score">Incremented score to be returned.</param>
        /// <param name="tier">tier.</param>
        /// <param name="userId">User ID of the user.</param>
        public LeaderboardsIncrementScoreResponse(decimal rank = default(decimal), double score = default(double), LeaderboardsTier tier = default(LeaderboardsTier), string userId = default(string))
        {
            this.Rank = rank;
            this.Score = score;
            this.Tier = tier;
            this.UserId = userId;
        }

        /// <summary>
        /// Latest rank to be returned
        /// </summary>
        /// <value>Latest rank to be returned</value>
        [DataMember(Name = "rank", EmitDefaultValue = false)]
        public decimal Rank { get; set; }

        /// <summary>
        /// Incremented score to be returned
        /// </summary>
        /// <value>Incremented score to be returned</value>
        [DataMember(Name = "score", EmitDefaultValue = false)]
        public double Score { get; set; }

        /// <summary>
        /// Gets or Sets Tier
        /// </summary>
        [DataMember(Name = "tier", EmitDefaultValue = false)]
        public LeaderboardsTier Tier { get; set; }

        /// <summary>
        /// User ID of the user
        /// </summary>
        /// <value>User ID of the user</value>
        [DataMember(Name = "user_id", EmitDefaultValue = false)]
        public string UserId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LeaderboardsIncrementScoreResponse {\n");
            sb.Append("  Rank: ").Append(Rank).Append("\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  Tier: ").Append(Tier).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as LeaderboardsIncrementScoreResponse);
        }

        /// <summary>
        /// Returns true if LeaderboardsIncrementScoreResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of LeaderboardsIncrementScoreResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(LeaderboardsIncrementScoreResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Rank == input.Rank ||
                    this.Rank.Equals(input.Rank)
                ) && 
                (
                    this.Score == input.Score ||
                    this.Score.Equals(input.Score)
                ) && 
                (
                    this.Tier == input.Tier ||
                    (this.Tier != null &&
                    this.Tier.Equals(input.Tier))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Rank.GetHashCode();
                hashCode = (hashCode * 59) + this.Score.GetHashCode();
                if (this.Tier != null)
                {
                    hashCode = (hashCode * 59) + this.Tier.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
