/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// ProfilesBatchGetProfilesResponse
    /// </summary>
    [DataContract(Name = "profilesBatchGetProfilesResponse")]
    public partial class ProfilesBatchGetProfilesResponse : IEquatable<ProfilesBatchGetProfilesResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProfilesBatchGetProfilesResponse" /> class.
        /// </summary>
        /// <param name="profiles">profiles.</param>
        /// <param name="responses">List of responses for each user ID.</param>
        public ProfilesBatchGetProfilesResponse(Dictionary<string, Object> profiles = default(Dictionary<string, Object>), List<ProfilesBatchGetProfilesSingleResponse> responses = default(List<ProfilesBatchGetProfilesSingleResponse>))
        {
            this.Profiles = profiles;
            this.Responses = responses;
        }

        /// <summary>
        /// Gets or Sets Profiles
        /// </summary>
        [DataMember(Name = "profiles", EmitDefaultValue = false)]
        public Dictionary<string, Object> Profiles { get; set; }

        /// <summary>
        /// List of responses for each user ID
        /// </summary>
        /// <value>List of responses for each user ID</value>
        [DataMember(Name = "responses", EmitDefaultValue = false)]
        public List<ProfilesBatchGetProfilesSingleResponse> Responses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ProfilesBatchGetProfilesResponse {\n");
            sb.Append("  Profiles: ").Append(Profiles).Append("\n");
            sb.Append("  Responses: ").Append(Responses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProfilesBatchGetProfilesResponse);
        }

        /// <summary>
        /// Returns true if ProfilesBatchGetProfilesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of ProfilesBatchGetProfilesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProfilesBatchGetProfilesResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Profiles == input.Profiles ||
                    this.Profiles != null &&
                    input.Profiles != null &&
                    this.Profiles.SequenceEqual(input.Profiles)
                ) && 
                (
                    this.Responses == input.Responses ||
                    this.Responses != null &&
                    input.Responses != null &&
                    this.Responses.SequenceEqual(input.Responses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Profiles != null)
                {
                    hashCode = (hashCode * 59) + this.Profiles.GetHashCode();
                }
                if (this.Responses != null)
                {
                    hashCode = (hashCode * 59) + this.Responses.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
