/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// ReplaceJsonBlobRequest
    /// </summary>
    [DataContract(Name = "ReplaceJsonBlob_request")]
    public partial class ReplaceJsonBlobRequest : IEquatable<ReplaceJsonBlobRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplaceJsonBlobRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ReplaceJsonBlobRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ReplaceJsonBlobRequest" /> class.
        /// </summary>
        /// <param name="cas">CAS value retrieved from the last operation.</param>
        /// <param name="create">Whether the json blob should be created if it doesn&#39;t exist.</param>
        /// <param name="ttl">Optional TTL for the json blob.</param>
        /// <param name="value">JSON value to be inserted (required).</param>
        public ReplaceJsonBlobRequest(string cas = default(string), bool create = default(bool), long ttl = default(long), Object value = default(Object))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for ReplaceJsonBlobRequest and cannot be null");
            }
            this.Value = value;
            this.Cas = cas;
            this.Create = create;
            this.Ttl = ttl;
        }

        /// <summary>
        /// CAS value retrieved from the last operation
        /// </summary>
        /// <value>CAS value retrieved from the last operation</value>
        [DataMember(Name = "cas", EmitDefaultValue = false)]
        public string Cas { get; set; }

        /// <summary>
        /// Whether the json blob should be created if it doesn&#39;t exist
        /// </summary>
        /// <value>Whether the json blob should be created if it doesn&#39;t exist</value>
        [DataMember(Name = "create", EmitDefaultValue = true)]
        public bool Create { get; set; }

        /// <summary>
        /// Optional TTL for the json blob
        /// </summary>
        /// <value>Optional TTL for the json blob</value>
        [DataMember(Name = "ttl", EmitDefaultValue = false)]
        public long Ttl { get; set; }

        /// <summary>
        /// JSON value to be inserted
        /// </summary>
        /// <value>JSON value to be inserted</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ReplaceJsonBlobRequest {\n");
            sb.Append("  Cas: ").Append(Cas).Append("\n");
            sb.Append("  Create: ").Append(Create).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ReplaceJsonBlobRequest);
        }

        /// <summary>
        /// Returns true if ReplaceJsonBlobRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of ReplaceJsonBlobRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ReplaceJsonBlobRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Cas == input.Cas ||
                    (this.Cas != null &&
                    this.Cas.Equals(input.Cas))
                ) && 
                (
                    this.Create == input.Create ||
                    this.Create.Equals(input.Create)
                ) && 
                (
                    this.Ttl == input.Ttl ||
                    this.Ttl.Equals(input.Ttl)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cas != null)
                {
                    hashCode = (hashCode * 59) + this.Cas.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Create.GetHashCode();
                hashCode = (hashCode * 59) + this.Ttl.GetHashCode();
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
