/*
 * snapship
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: snapship: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// SetScoreRequest
    /// </summary>
    [DataContract(Name = "SetScore_request")]
    public partial class SetScoreRequest : IEquatable<SetScoreRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetScoreRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetScoreRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetScoreRequest" /> class.
        /// </summary>
        /// <param name="score">New score to be inserted (required).</param>
        /// <param name="tierName">Name of the tier.</param>
        public SetScoreRequest(double score = default(double), string tierName = default(string))
        {
            this.Score = score;
            this.TierName = tierName;
        }

        /// <summary>
        /// New score to be inserted
        /// </summary>
        /// <value>New score to be inserted</value>
        [DataMember(Name = "score", IsRequired = true, EmitDefaultValue = true)]
        public double Score { get; set; }

        /// <summary>
        /// Name of the tier
        /// </summary>
        /// <value>Name of the tier</value>
        [DataMember(Name = "tier_name", EmitDefaultValue = false)]
        public string TierName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetScoreRequest {\n");
            sb.Append("  Score: ").Append(Score).Append("\n");
            sb.Append("  TierName: ").Append(TierName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetScoreRequest);
        }

        /// <summary>
        /// Returns true if SetScoreRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SetScoreRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetScoreRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Score == input.Score ||
                    this.Score.Equals(input.Score)
                ) && 
                (
                    this.TierName == input.TierName ||
                    (this.TierName != null &&
                    this.TierName.Equals(input.TierName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Score.GetHashCode();
                if (this.TierName != null)
                {
                    hashCode = (hashCode * 59) + this.TierName.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
