/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// SetUserStatisticRequest
    /// </summary>
    [DataContract(Name = "SetUserStatistic_request")]
    public partial class SetUserStatisticRequest : IEquatable<SetUserStatisticRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetUserStatisticRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetUserStatisticRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetUserStatisticRequest" /> class.
        /// </summary>
        /// <param name="value">Value to set the statistic to (required).</param>
        public SetUserStatisticRequest(string value = default(string))
        {
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for SetUserStatisticRequest and cannot be null");
            }
            this.Value = value;
        }

        /// <summary>
        /// Value to set the statistic to
        /// </summary>
        /// <value>Value to set the statistic to</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetUserStatisticRequest {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetUserStatisticRequest);
        }

        /// <summary>
        /// Returns true if SetUserStatisticRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SetUserStatisticRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetUserStatisticRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
