/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StatisticsBatchSetUserStatisticsResponse
    /// </summary>
    [DataContract(Name = "statisticsBatchSetUserStatisticsResponse")]
    public partial class StatisticsBatchSetUserStatisticsResponse : IEquatable<StatisticsBatchSetUserStatisticsResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsBatchSetUserStatisticsResponse" /> class.
        /// </summary>
        /// <param name="responses">responses.</param>
        /// <param name="userStatistics">userStatistics.</param>
        public StatisticsBatchSetUserStatisticsResponse(List<StatisticsBatchSetUserStatisticsSingleResponse> responses = default(List<StatisticsBatchSetUserStatisticsSingleResponse>), List<StatisticsUserStatistic> userStatistics = default(List<StatisticsUserStatistic>))
        {
            this.Responses = responses;
            this.UserStatistics = userStatistics;
        }

        /// <summary>
        /// Gets or Sets Responses
        /// </summary>
        [DataMember(Name = "responses", EmitDefaultValue = false)]
        public List<StatisticsBatchSetUserStatisticsSingleResponse> Responses { get; set; }

        /// <summary>
        /// Gets or Sets UserStatistics
        /// </summary>
        [DataMember(Name = "user_statistics", EmitDefaultValue = false)]
        public List<StatisticsUserStatistic> UserStatistics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatisticsBatchSetUserStatisticsResponse {\n");
            sb.Append("  Responses: ").Append(Responses).Append("\n");
            sb.Append("  UserStatistics: ").Append(UserStatistics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StatisticsBatchSetUserStatisticsResponse);
        }

        /// <summary>
        /// Returns true if StatisticsBatchSetUserStatisticsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StatisticsBatchSetUserStatisticsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatisticsBatchSetUserStatisticsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Responses == input.Responses ||
                    this.Responses != null &&
                    input.Responses != null &&
                    this.Responses.SequenceEqual(input.Responses)
                ) && 
                (
                    this.UserStatistics == input.UserStatistics ||
                    this.UserStatistics != null &&
                    input.UserStatistics != null &&
                    this.UserStatistics.SequenceEqual(input.UserStatistics)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Responses != null)
                {
                    hashCode = (hashCode * 59) + this.Responses.GetHashCode();
                }
                if (this.UserStatistics != null)
                {
                    hashCode = (hashCode * 59) + this.UserStatistics.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
