/*
 * snapship
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: snapship: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StatisticsGetUserStatisticsResponse
    /// </summary>
    [DataContract(Name = "statisticsGetUserStatisticsResponse")]
    public partial class StatisticsGetUserStatisticsResponse : IEquatable<StatisticsGetUserStatisticsResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsGetUserStatisticsResponse" /> class.
        /// </summary>
        /// <param name="userStatistics">userStatistics.</param>
        public StatisticsGetUserStatisticsResponse(List<StatisticsUserStatistic> userStatistics = default(List<StatisticsUserStatistic>))
        {
            this.UserStatistics = userStatistics;
        }

        /// <summary>
        /// Gets or Sets UserStatistics
        /// </summary>
        [DataMember(Name = "user_statistics", EmitDefaultValue = false)]
        public List<StatisticsUserStatistic> UserStatistics { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatisticsGetUserStatisticsResponse {\n");
            sb.Append("  UserStatistics: ").Append(UserStatistics).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StatisticsGetUserStatisticsResponse);
        }

        /// <summary>
        /// Returns true if StatisticsGetUserStatisticsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StatisticsGetUserStatisticsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatisticsGetUserStatisticsResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.UserStatistics == input.UserStatistics ||
                    this.UserStatistics != null &&
                    input.UserStatistics != null &&
                    this.UserStatistics.SequenceEqual(input.UserStatistics)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserStatistics != null)
                {
                    hashCode = (hashCode * 59) + this.UserStatistics.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
