/*
 * snapship
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: snapship: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Snapser.Client.FileParameter;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StatisticsIsUserInSegmentResponse
    /// </summary>
    [DataContract(Name = "statisticsIsUserInSegmentResponse")]
    public partial class StatisticsIsUserInSegmentResponse : IEquatable<StatisticsIsUserInSegmentResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StatisticsIsUserInSegmentResponse" /> class.
        /// </summary>
        /// <param name="userInSegment">userInSegment.</param>
        public StatisticsIsUserInSegmentResponse(bool userInSegment = default(bool))
        {
            this.UserInSegment = userInSegment;
        }

        /// <summary>
        /// Gets or Sets UserInSegment
        /// </summary>
        [DataMember(Name = "userInSegment", EmitDefaultValue = true)]
        public bool UserInSegment { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StatisticsIsUserInSegmentResponse {\n");
            sb.Append("  UserInSegment: ").Append(UserInSegment).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StatisticsIsUserInSegmentResponse);
        }

        /// <summary>
        /// Returns true if StatisticsIsUserInSegmentResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StatisticsIsUserInSegmentResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StatisticsIsUserInSegmentResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.UserInSegment == input.UserInSegment ||
                    this.UserInSegment.Equals(input.UserInSegment)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.UserInSegment.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
