/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v1 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StorageUserBlobResponse
    /// </summary>
    [DataContract(Name = "storageUserBlobResponse")]
    public partial class StorageUserBlobResponse : IEquatable<StorageUserBlobResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageUserBlobResponse" /> class.
        /// </summary>
        /// <param name="cas">CAS value used for future operations.</param>
        /// <param name="ownerId">Blob owner&#39;s user ID.</param>
        /// <param name="value">Blob value.</param>
        public StorageUserBlobResponse(string cas = default(string), string ownerId = default(string), string value = default(string))
        {
            this.Cas = cas;
            this.OwnerId = ownerId;
            this.Value = value;
        }

        /// <summary>
        /// CAS value used for future operations
        /// </summary>
        /// <value>CAS value used for future operations</value>
        [DataMember(Name = "cas", EmitDefaultValue = false)]
        public string Cas { get; set; }

        /// <summary>
        /// Blob owner&#39;s user ID
        /// </summary>
        /// <value>Blob owner&#39;s user ID</value>
        [DataMember(Name = "owner_id", EmitDefaultValue = false)]
        public string OwnerId { get; set; }

        /// <summary>
        /// Blob value
        /// </summary>
        /// <value>Blob value</value>
        [DataMember(Name = "value", EmitDefaultValue = false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageUserBlobResponse {\n");
            sb.Append("  Cas: ").Append(Cas).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StorageUserBlobResponse);
        }

        /// <summary>
        /// Returns true if StorageUserBlobResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StorageUserBlobResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageUserBlobResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Cas == input.Cas ||
                    (this.Cas != null &&
                    this.Cas.Equals(input.Cas))
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cas != null)
                {
                    hashCode = (hashCode * 59) + this.Cas.GetHashCode();
                }
                if (this.OwnerId != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerId.GetHashCode();
                }
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
