/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StorageReplaceJsonBlobResponse
    /// </summary>
    [DataContract(Name = "storageReplaceJsonBlobResponse")]
    public partial class StorageReplaceJsonBlobResponse : IEquatable<StorageReplaceJsonBlobResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageReplaceJsonBlobResponse" /> class.
        /// </summary>
        /// <param name="cas">CAS value used for future operations.</param>
        public StorageReplaceJsonBlobResponse(string cas = default(string))
        {
            this.Cas = cas;
        }

        /// <summary>
        /// CAS value used for future operations
        /// </summary>
        /// <value>CAS value used for future operations</value>
        [DataMember(Name = "cas", EmitDefaultValue = false)]
        public string Cas { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageReplaceJsonBlobResponse {\n");
            sb.Append("  Cas: ").Append(Cas).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StorageReplaceJsonBlobResponse);
        }

        /// <summary>
        /// Returns true if StorageReplaceJsonBlobResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of StorageReplaceJsonBlobResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageReplaceJsonBlobResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Cas == input.Cas ||
                    (this.Cas != null &&
                    this.Cas.Equals(input.Cas))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Cas != null)
                {
                    hashCode = (hashCode * 59) + this.Cas.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
