/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StorageInsertJsonBlobRequest
    /// </summary>
    [DataContract(Name = "storageInsertJsonBlobRequest")]
    public partial class StorageInsertJsonBlobRequest : IEquatable<StorageInsertJsonBlobRequest>
    {
        /// <summary>
        /// Access to the blob. (public/protected/private)
        /// </summary>
        /// <value>Access to the blob. (public/protected/private)</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AccessTypeEnum
        {
            /// <summary>
            /// Enum Public for value: public
            /// </summary>
            [EnumMember(Value = "public")]
            Public = 1,

            /// <summary>
            /// Enum Private for value: private
            /// </summary>
            [EnumMember(Value = "private")]
            Private = 2,

            /// <summary>
            /// Enum Protected for value: protected
            /// </summary>
            [EnumMember(Value = "protected")]
            Protected = 3
        }


        /// <summary>
        /// Access to the blob. (public/protected/private)
        /// </summary>
        /// <value>Access to the blob. (public/protected/private)</value>
        [DataMember(Name = "access_type", IsRequired = true, EmitDefaultValue = true)]
        public AccessTypeEnum AccessType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageInsertJsonBlobRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StorageInsertJsonBlobRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageInsertJsonBlobRequest" /> class.
        /// </summary>
        /// <param name="accessType">Access to the blob. (public/protected/private) (required).</param>
        /// <param name="jsonBlobKey">Blob key (required).</param>
        /// <param name="ownerId">Blob owner&#39;s user ID (required).</param>
        /// <param name="ttl">Optional TTL for the blob.</param>
        /// <param name="value">JSON value to be inserted (required).</param>
        public StorageInsertJsonBlobRequest(AccessTypeEnum accessType = default(AccessTypeEnum), string jsonBlobKey = default(string), string ownerId = default(string), long ttl = default(long), Object value = default(Object))
        {
            this.AccessType = accessType;
            // to ensure "jsonBlobKey" is required (not null)
            if (jsonBlobKey == null)
            {
                throw new ArgumentNullException("jsonBlobKey is a required property for StorageInsertJsonBlobRequest and cannot be null");
            }
            this.JsonBlobKey = jsonBlobKey;
            // to ensure "ownerId" is required (not null)
            if (ownerId == null)
            {
                throw new ArgumentNullException("ownerId is a required property for StorageInsertJsonBlobRequest and cannot be null");
            }
            this.OwnerId = ownerId;
            // to ensure "value" is required (not null)
            if (value == null)
            {
                throw new ArgumentNullException("value is a required property for StorageInsertJsonBlobRequest and cannot be null");
            }
            this.Value = value;
            this.Ttl = ttl;
        }

        /// <summary>
        /// Blob key
        /// </summary>
        /// <value>Blob key</value>
        [DataMember(Name = "json_blob_key", IsRequired = true, EmitDefaultValue = true)]
        public string JsonBlobKey { get; set; }

        /// <summary>
        /// Blob owner&#39;s user ID
        /// </summary>
        /// <value>Blob owner&#39;s user ID</value>
        [DataMember(Name = "owner_id", IsRequired = true, EmitDefaultValue = true)]
        public string OwnerId { get; set; }

        /// <summary>
        /// Optional TTL for the blob
        /// </summary>
        /// <value>Optional TTL for the blob</value>
        [DataMember(Name = "ttl", EmitDefaultValue = false)]
        public long Ttl { get; set; }

        /// <summary>
        /// JSON value to be inserted
        /// </summary>
        /// <value>JSON value to be inserted</value>
        [DataMember(Name = "value", IsRequired = true, EmitDefaultValue = true)]
        public Object Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageInsertJsonBlobRequest {\n");
            sb.Append("  AccessType: ").Append(AccessType).Append("\n");
            sb.Append("  JsonBlobKey: ").Append(JsonBlobKey).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  Ttl: ").Append(Ttl).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StorageInsertJsonBlobRequest);
        }

        /// <summary>
        /// Returns true if StorageInsertJsonBlobRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of StorageInsertJsonBlobRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageInsertJsonBlobRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AccessType == input.AccessType ||
                    this.AccessType.Equals(input.AccessType)
                ) && 
                (
                    this.JsonBlobKey == input.JsonBlobKey ||
                    (this.JsonBlobKey != null &&
                    this.JsonBlobKey.Equals(input.JsonBlobKey))
                ) && 
                (
                    this.OwnerId == input.OwnerId ||
                    (this.OwnerId != null &&
                    this.OwnerId.Equals(input.OwnerId))
                ) && 
                (
                    this.Ttl == input.Ttl ||
                    this.Ttl.Equals(input.Ttl)
                ) && 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.AccessType.GetHashCode();
                if (this.JsonBlobKey != null)
                {
                    hashCode = (hashCode * 59) + this.JsonBlobKey.GetHashCode();
                }
                if (this.OwnerId != null)
                {
                    hashCode = (hashCode * 59) + this.OwnerId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Ttl.GetHashCode();
                if (this.Value != null)
                {
                    hashCode = (hashCode * 59) + this.Value.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
