/*
 * my-dev-cluster
 *
 * Your custom SDK
 *
 * The version of the OpenAPI document: my-dev-cluster: v6 SDK
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using OpenAPIDateConverter = Snapser.Client.OpenAPIDateConverter;

namespace Snapser.Model
{
    /// <summary>
    /// StorageBatchAppendArrSubDocumentsRequest
    /// </summary>
    [DataContract(Name = "storageBatchAppendArrSubDocumentsRequest")]
    public partial class StorageBatchAppendArrSubDocumentsRequest : IEquatable<StorageBatchAppendArrSubDocumentsRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageBatchAppendArrSubDocumentsRequest" /> class.
        /// </summary>
        /// <param name="subDocuments">subDocuments.</param>
        public StorageBatchAppendArrSubDocumentsRequest(List<StorageAppendArrSubDocumentRequest> subDocuments = default(List<StorageAppendArrSubDocumentRequest>))
        {
            this.SubDocuments = subDocuments;
        }

        /// <summary>
        /// Gets or Sets SubDocuments
        /// </summary>
        [DataMember(Name = "sub_documents", EmitDefaultValue = false)]
        public List<StorageAppendArrSubDocumentRequest> SubDocuments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StorageBatchAppendArrSubDocumentsRequest {\n");
            sb.Append("  SubDocuments: ").Append(SubDocuments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StorageBatchAppendArrSubDocumentsRequest);
        }

        /// <summary>
        /// Returns true if StorageBatchAppendArrSubDocumentsRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of StorageBatchAppendArrSubDocumentsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageBatchAppendArrSubDocumentsRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.SubDocuments == input.SubDocuments ||
                    this.SubDocuments != null &&
                    input.SubDocuments != null &&
                    this.SubDocuments.SequenceEqual(input.SubDocuments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SubDocuments != null)
                {
                    hashCode = (hashCode * 59) + this.SubDocuments.GetHashCode();
                }
                return hashCode;
            }
        }

    }

}
